version: "3.3"
services:
  ifm3d_ros:
    tty: true
    image: ifm3d_ros_arm64:debug
    environment:
      - ROS_IP=192.168.0.69
      - ROS_MASTER_URI=http://192.168.0.69:11311
    network_mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        mode: non-blocking
        max-buffer-size: "200m"
    command:
      - /bin/bash
      - -c
      - |
        (. /opt/ros/noetic/setup.sh;
        . /home/ifm/catkin_ws/devel/setup.sh;
        export ROS_IP="192.168.0.69";
        export ROS_MASTER_URI=http://192.168.0.69:11311;
        echo $ROS_MASTER_URI;
        echo $ROS_IP;
        roscore -p 11311;
        roslaunch ifm3d_ros_driver camera_3d.launch pcic_port:=50012 --wait)
