version: "2.3"
services:

  ifm3d_ros_listener:
    tty: true
    image: ifm3d-ros:noetic-amd64_v8

    restart: unless-stopped
    volumes:
      - ./hosts_IPC:/etc/hosts/

    logging:
      driver: "json-file"
      options:
        mode: non-blocking
        max-buffer-size: "20m"

    command:
      - /bin/bash
      - -c
      - |
        set -a
        . /opt/ros/noetic/setup.sh;
        . /home/ifm/catkin_ws/devel/setup.sh;
        export ROS_MASTER_URI=http://ifm3d_rosmaster:11311;
        export ROS_HOSTNAME=ifm3d_ros_listener;
        echo ROS_MASTER_URI=$$ROS_MASTER_URI;
        echo ROS_IP=$$ROS_IP;

    network_mode: host
