version: "2.3"
services:
  ifm3d_ros:
    tty: true
    image: ifm3d-ros:noetic-arm64_v8

    restart: unless-stopped
    volumes:
      - ./launch/four_cameras.launch:/home/ifm/catkin_ws/src/ifm3d_ros_driver/launch/four_cameras.launch
      - ./hosts_ros_master:/etc/hosts/

    logging:
      driver: "json-file"
      options:
        mode: non-blocking
        max-buffer-size: "20m"

    command:
      - /bin/bash
      - -c
      - |
        set -a
        . /opt/ros/noetic/setup.sh;
        . /home/ifm/catkin_ws/devel/setup.sh;
        export IFM3D_IP="127.0.0.1";
        export GLOG_logtostderr=1;
        export GLOG_minloglevel=3;
        export ROS_MASTER_URI=http://ifm3d_rosmaster:11311;
        export ROS_HOSTNAME=ifm3d_ros;
        echo ROOS_MASTER_URI=$$ROS_MASTER_URI;
        echo ROS_HOSTNAME=$$ROS_HOSTNAME;
        roslaunch ifm3d_ros_driver four_cameras.launch --wait -t 10

    network_mode: host
